// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/ivantedja/xmarvel/entity"
	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Search provides a mock function with given fields: ctx
func (_m *Usecase) Search(ctx context.Context) ([]*entity.Character, error) {
	ret := _m.Called(ctx)

	var r0 []*entity.Character
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Character); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Character)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
